In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0] > 0.5:
        print('Rock')
    elif prediction[0][1] > 0.5:
        print('Paper')
    elif prediction[0][2] > 0.5:
        print('Scissors')
    else:
        print('Nothing')
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()


2022-07-04 11:50:57.218311: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/someone/anaconda3/envs/rps_env/lib/python3.8/site-packages/cv2/../../lib64:/app/lib
2022-07-04 11:50:57.218350: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-07-04 11:51:00.483262: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-07-04 11:51:00.484016: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/someone/anaconda3/envs/rps_env

1/1 [==============================] - 1s 1s/step
Paper


Qt: Session management error: None of the authentication protocols specified are supported


[[1.0536404e-02 9.8799628e-01 2.2512863e-07 1.4670730e-03]]
1/1 [==============================] - 0s 59ms/step
Rock
[[9.9124813e-01 4.7876674e-04 1.6778291e-05 8.2562584e-03]]
1/1 [==============================] - 0s 47ms/step
Nothing
[[0.25513828 0.2907472  0.00057212 0.4535424 ]]
1/1 [==============================] - 0s 48ms/step
Nothing
[[0.22492625 0.14761534 0.00128004 0.62617844]]
1/1 [==============================] - 0s 50ms/step
Nothing
[[0.14893338 0.18507235 0.00159386 0.6644004 ]]
1/1 [==============================] - 0s 50ms/step
Rock
[[0.5406063  0.01939562 0.00616735 0.43383068]]
1/1 [==============================] - 0s 50ms/step
Nothing
[[0.35829192 0.04290503 0.00870597 0.59009707]]
1/1 [==============================] - 0s 50ms/step
Nothing
[[0.18684034 0.07552686 0.01046843 0.7271643 ]]
1/1 [==============================] - 0s 48ms/step
Nothing
[[0.38895366 0.01553521 0.01426639 0.58124477]]
1/1 [==============================] - 0s 47ms/step
Rock
[[0.5029217  

KeyboardInterrupt: 