In [2]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()


1/1 [==============================] - 1s 1s/step
[[3.8248149e-01 6.1577493e-01 1.2143361e-06 1.7423127e-03]]
1/1 [==============================] - 0s 52ms/step
[[6.6891664e-01 3.2922623e-01 1.5130012e-05 1.8420486e-03]]
1/1 [==============================] - 0s 67ms/step
[[0.5695632  0.04303146 0.37917253 0.00823273]]
1/1 [==============================] - 0s 41ms/step
[[0.31007132 0.04941125 0.6331207  0.00739668]]
1/1 [==============================] - 0s 49ms/step
[[0.36053476 0.0376825  0.5926302  0.00915254]]
1/1 [==============================] - 0s 51ms/step
[[0.5715844  0.00759049 0.41922614 0.00159895]]
1/1 [==============================] - 0s 50ms/step
[[0.5663178  0.00543263 0.42641923 0.00183037]]
1/1 [==============================] - 0s 48ms/step
[[0.29507968 0.01095278 0.6918182  0.00214935]]
1/1 [==============================] - 0s 50ms/step
[[0.35057378 0.01836064 0.6280694  0.00299622]]
1/1 [==============================] - 0s 51ms/step
[[0.44021416 0.00440756 0.