In [29]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0] > 0.5:
        print('rock')
    elif prediction[0][1] > 0.5:
        print('paper')
    elif prediction[0][2] > 0.5:
        print('scissors')
    else:
        print('Nothing')
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()


1/1 [==============================] - 1s 1s/step
Paper
[[1.5860907e-05 9.9998164e-01 3.9359693e-09 2.4919379e-06]]
1/1 [==============================] - 0s 53ms/step
Paper
[[5.9593054e-05 9.9993467e-01 2.4695991e-08 5.6992781e-06]]
1/1 [==============================] - 0s 54ms/step
Paper
[[2.1538783e-05 9.9997485e-01 1.6266677e-08 3.6220879e-06]]
1/1 [==============================] - 0s 48ms/step
Paper
[[1.4154062e-05 9.9998415e-01 3.0582790e-08 1.7135818e-06]]
1/1 [==============================] - 0s 45ms/step
Paper
[[4.8867427e-05 9.9994636e-01 3.7125869e-08 4.7184521e-06]]
1/1 [==============================] - 0s 42ms/step
Paper
[[4.6454074e-06 9.9999344e-01 3.4980367e-08 1.9146250e-06]]
1/1 [==============================] - 0s 41ms/step
Paper
[[7.9867768e-06 9.9998963e-01 6.7186363e-08 2.2594181e-06]]
1/1 [==============================] - 0s 47ms/step
Paper
[[7.918144e-06 9.999889e-01 4.519684e-08 3.271194e-06]]
1/1 [==============================] - 0s 48ms/step
Paper
[[2.

In [5]:
import time
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

init_time = time.time()

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    
    if time.time() >= init_time + 3: 
        init_time = time.time()

        if prediction[0][0] > 0.5:
            print('rock')
        elif prediction[0][1] > 0.5:
            print('paper')
        elif prediction[0][2] > 0.5:
            print('scissors')
        else:
            print('Nothing')
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()


1/1 [==============================] - 1s 1s/step
[[8.7837523e-01 3.6910553e-02 8.1811089e-04 8.3896153e-02]]
1/1 [==============================] - 0s 46ms/step
[[9.2274016e-01 1.0938082e-02 4.1569164e-04 6.5905988e-02]]
1/1 [==============================] - 0s 57ms/step
[[9.8036778e-01 4.2529767e-03 7.7163789e-04 1.4607618e-02]]
1/1 [==============================] - 0s 50ms/step
[[9.6301067e-01 2.0151261e-02 9.2493102e-04 1.5913045e-02]]
1/1 [==============================] - 0s 56ms/step
[[0.9583883  0.02645601 0.00097182 0.01418382]]
1/1 [==============================] - 0s 47ms/step
[[5.0454628e-01 4.3719235e-01 2.2010747e-04 5.8041293e-02]]
1/1 [==============================] - 0s 48ms/step
[[4.5811638e-01 5.3932810e-01 2.6417538e-05 2.5291266e-03]]
1/1 [==============================] - 0s 38ms/step
[[9.7246164e-01 1.1390575e-02 9.4411007e-05 1.6053393e-02]]
1/1 [==============================] - 0s 41ms/step
[[9.803593e-01 9.696175e-03 7.656526e-05 9.867968e-03]]
1/1 [=====

In [16]:
class User:

    def __init__(self):
        self.user_choice = user_choice

    def get(self):
        self.user_choice = input('choose')
    
    def __repr__(self):
        return self.user_choice


a = User
a.get()
a.show()

TypeError: get() missing 1 required positional argument: 'self'